language: node_js
node_js:
  - 11.1.0
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  token:
    secure: CJDcM1IoJgsl3r5Hy/ME3OZvyCzwivPT8Ur+90lRLJyT0/WWUdCTN9shYLeVzAE0EdbVxKiZFNSHhGF3VAPxbTBK2EZ/t71AXqJdkSB6vTTVmtgrK6RNrReveyWKvwv2hFuuUisqF8PvcR6H3M0nbPJhmN1CSgN6G5qWTvpWJ93hxQInJa1T2FzhWHloLODjL34SmH2RlrGhI7iPvobz/7A1oyeYIvflMAYPiShqo3iMBrYH1zA2oW21Wcw7xrJuUOSZbDLR/RHk7aPp8Dle/kHBk09X9bJIxHziVs/460mALIgj02mFuKphpJMvw5qAHGIEeY80icdsHiLWl7bGl7k1KlMkovKJSVN4hs3ihrT4evI5uQLZC9o+WmT+5THsirrur5QayYMgl/DRBks77KzH6e0RXzPQ2eN2oal3/Ze2VN+5WYhgReEXLymgfuWVPX8sCvQAQtiYb/5Fki8PM4VYqLYYGgE2nfwXmq4YXvjU411SezokVGhr99eF5Wy3bjMNzpSaMyT8xT25PMaplEZsgYVOlr28arNK4f/bXLlwPwaDXIc28MjAE3BRlAD/pTNmEeGaIJ94MlH1kqx7XVOtfPPZft7dO15Y3rry2fd4xv5jV1C075HMPgyE+InB4RjPrBtNaVqNgiH37i7jtWW4ncD73W+GM0NmryBwP3M=
